# Generated by Django 3.1 on 2023-11-14 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='calle',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='ciudad',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='codigo_postal',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='colonia',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='correo_electronico',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='entre_calles',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='estado',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='numero_exterior',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='numero_interior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='referencias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='telefono',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
