# Generated by Django 4.2.7 on 2023-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0003_auto_20231113_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='entre_calles',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='numero_exterior',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='numero_interior',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='referencias',
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
