# Generated by Django 4.2.7 on 2024-03-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0004_remove_contribuyente_calle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribuyente',
            options={'verbose_name': 'Contribuyente', 'verbose_name_plural': 'Contribuyentes'},
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='folio_unico',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='correo_electronico',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
