# Generated by Django 4.2.7 on 2024-03-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0005_alter_contribuyente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='folio_unico',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
