# Generated by Django 4.2.7 on 2024-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0006_alter_contribuyente_folio_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='folio_unico',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
