# Generated by Django 4.2.7 on 2024-03-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0010_alter_contribuyente_folio_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='folio_unico',
        ),
    ]
