# Generated by Django 4.2.7 on 2024-03-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0013_contribuyente_curp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuyente',
            old_name='materno',
            new_name='apellido_materno',
        ),
    ]
