# Generated by Django 4.2.7 on 2024-08-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribuyentes', '0014_rename_materno_contribuyente_apellido_materno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
