# Generated by Django 4.2.7 on 2023-11-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tarifas', '0001_initial'),
        ('Propiedades', '0004_propiedad_tipo_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('adeudo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mes_pago', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Propiedades.propiedad')),
                ('tarifa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Tarifas.tarifa')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
