# Generated by Django 4.2.7 on 2023-12-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
        ('Recibos', '0004_alter_tipopago_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Servicios.servicio'),
        ),
    ]
