# Generated by Django 4.2.7 on 2024-05-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recibos', '0005_pago_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='adeudo',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='pago',
        ),
        migrations.AddField(
            model_name='pago',
            name='recibo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Recibos.recibo'),
        ),
    ]
