# Generated by Django 4.2.7 on 2024-05-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recibos', '0006_remove_pago_adeudo_remove_recibo_pago_pago_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='recibo',
            name='tipo_pago',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Recibos.tipopago'),
        ),
    ]
