# Generated by Django 4.2.7 on 2024-07-29 07:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PreguntasFrecuentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
