# Generated by Django 3.1 on 2023-11-14 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contribuyentes', '0003_auto_20231113_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interior', models.TextField(blank=True, null=True)),
                ('numero_exterior', models.TextField(default=None)),
                ('calle', models.TextField(default=None)),
                ('entre_calles', models.TextField(default=None)),
                ('colonia', models.TextField(default=None)),
                ('ciudad', models.TextField(default=None)),
                ('estado', models.TextField(default=None)),
                ('codigo_postal', models.CharField(default=None, max_length=10)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('contribuyente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Contribuyentes.contribuyente')),
            ],
        ),
    ]
