# Generated by Django 3.1 on 2023-11-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0002_auto_20231113_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo_Propiedad',
            new_name='TipoPropiedad',
        ),
    ]
