# Generated by Django 3.1 on 2023-11-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0003_auto_20231113_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Propiedades.tipopropiedad'),
        ),
    ]
