# Generated by Django 4.2.7 on 2024-03-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propiedades', '0005_alter_propiedad_id_alter_tipopropiedad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopropiedad',
            name='descripcion',
            field=models.TextField(default=None),
        ),
    ]
