# Generated by Django 4.2.7 on 2023-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
